[2025-04-06T13:08:51.107+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-06T13:08:51.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-06T12:50:00+00:00 [queued]>
[2025-04-06T13:08:51.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-06T12:50:00+00:00 [queued]>
[2025-04-06T13:08:51.200+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-06T13:08:51.241+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-06 12:50:00+00:00
[2025-04-06T13:08:51.259+0000] {standard_task_runner.py:63} INFO - Started process 237 to run task
[2025-04-06T13:08:51.269+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-06T12:50:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpuzvesie1']
[2025-04-06T13:08:51.276+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask run_iot_producer_script
[2025-04-06T13:08:51.398+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-06T12:50:00+00:00 [running]> on host aef507eba48f
[2025-04-06T13:08:51.581+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-06T12:50:00+00:00'
[2025-04-06T13:08:51.582+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-06T13:08:51.631+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-06T13:08:51.633+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-06T13:08:51.670+0000] {subprocess.py:86} INFO - Output:
[2025-04-06T13:08:55.880+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-06T13:08:55.881+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 13, in <module>
[2025-04-06T13:08:55.881+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-04-06T13:08:55.881+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2025-04-06T13:08:55.886+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-04-06T13:08:55.887+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 234, in __init__
[2025-04-06T13:08:55.896+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2025-04-06T13:08:55.897+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 929, in check_version
[2025-04-06T13:08:55.898+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-04-06T13:08:55.898+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-04-06T13:08:56.211+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-06T13:08:56.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-06T13:08:56.227+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-06T13:08:56.232+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-06T12:50:00+00:00, execution_date=20250406T125000, start_date=20250406T130851, end_date=20250406T130856
[2025-04-06T13:08:56.251+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 237)
[2025-04-06T13:08:56.269+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-06T13:08:56.299+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T13:08:56.302+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
