[2025-04-17T23:01:59.948+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-17T23:01:59.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-17T22:55:00+00:00 [queued]>
[2025-04-17T23:02:00.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-17T22:55:00+00:00 [queued]>
[2025-04-17T23:02:00.009+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-17T23:02:00.026+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-17 22:55:00+00:00
[2025-04-17T23:02:00.030+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2025-04-17T23:02:00.032+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-17T22:55:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmp19fv1vl3']
[2025-04-17T23:02:00.034+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask run_iot_producer_script
[2025-04-17T23:02:00.070+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-17T22:55:00+00:00 [running]> on host 2b5f93c9e322
[2025-04-17T23:02:00.136+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T22:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T22:55:00+00:00'
[2025-04-17T23:02:00.137+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-17T23:02:00.151+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-17T23:02:00.152+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-17T23:02:00.158+0000] {subprocess.py:86} INFO - Output:
[2025-04-17T23:02:16.649+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-17T23:02:16.650+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 12, in <module>
[2025-04-17T23:02:16.651+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-04-17T23:02:16.652+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2025-04-17T23:02:16.656+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-04-17T23:02:16.657+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 234, in __init__
[2025-04-17T23:02:16.657+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2025-04-17T23:02:16.658+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 929, in check_version
[2025-04-17T23:02:16.659+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-04-17T23:02:16.659+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-04-17T23:02:16.688+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-17T23:02:16.689+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-17T23:02:16.697+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T23:02:16.699+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-17T22:55:00+00:00, execution_date=20250417T225500, start_date=20250417T230159, end_date=20250417T230216
[2025-04-17T23:02:16.708+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 222)
[2025-04-17T23:02:16.753+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-17T23:02:16.768+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T23:02:16.769+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
