[2025-04-07T02:51:00.365+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T02:51:00.522+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_airflow_spark.run_spark_job manual__2025-04-07T02:50:58.045571+00:00 [queued]>
[2025-04-07T02:51:00.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_airflow_spark.run_spark_job manual__2025-04-07T02:50:58.045571+00:00 [queued]>
[2025-04-07T02:51:00.539+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-07T02:51:00.567+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_job> on 2025-04-07 02:50:58.045571+00:00
[2025-04-07T02:51:00.578+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_***_spark', 'run_spark_job', 'manual__2025-04-07T02:50:58.045571+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/spark_test.py', '--cfg-path', '/tmp/tmpoi340iki']
[2025-04-07T02:51:00.582+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask run_spark_job
[2025-04-07T02:51:00.584+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=22343) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-07T02:51:00.585+0000] {standard_task_runner.py:64} INFO - Started process 22344 to run task
[2025-04-07T02:51:00.659+0000] {task_command.py:426} INFO - Running <TaskInstance: test_airflow_spark.run_spark_job manual__2025-04-07T02:50:58.045571+00:00 [running]> on host 42c88f897c40
[2025-04-07T02:51:00.831+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_***_spark' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T02:50:58.045571+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T02:50:58.045571+00:00'
[2025-04-07T02:51:00.834+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T02:51:00.921+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T02:51:00.924+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spark_test.py", line 14, in submit_spark_job
    result = subprocess.run(spark_submit_cmd, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-04-07T02:51:00.960+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=test_***_spark, task_id=run_spark_job, run_id=manual__2025-04-07T02:50:58.045571+00:00, execution_date=20250407T025058, start_date=20250407T025100, end_date=20250407T025100
[2025-04-07T02:51:00.982+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task run_spark_job ([Errno 13] Permission denied: 'spark-submit'; 22344)
[2025-04-07T02:51:01.004+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-04-07T02:51:01.031+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T02:51:01.034+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
