[2025-03-26T11:17:26.877+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T11:17:26.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_airflow_spark.run_spark_job manual__2025-03-26T11:17:25.785500+00:00 [queued]>
[2025-03-26T11:17:26.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_airflow_spark.run_spark_job manual__2025-03-26T11:17:25.785500+00:00 [queued]>
[2025-03-26T11:17:26.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T11:17:26.939+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_spark_job> on 2025-03-26 11:17:25.785500+00:00
[2025-03-26T11:17:26.948+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_***_spark', 'run_spark_job', 'manual__2025-03-26T11:17:25.785500+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/spark_test.py', '--cfg-path', '/tmp/tmpbcz7i6_f']
[2025-03-26T11:17:26.950+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask run_spark_job
[2025-03-26T11:17:26.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4571) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:17:26.952+0000] {standard_task_runner.py:64} INFO - Started process 4572 to run task
[2025-03-26T11:17:26.996+0000] {task_command.py:426} INFO - Running <TaskInstance: test_airflow_spark.run_spark_job manual__2025-03-26T11:17:25.785500+00:00 [running]> on host d53f18eaa4d6
[2025-03-26T11:17:27.091+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_***_spark' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T11:17:25.785500+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T11:17:25.785500+00:00'
[2025-03-26T11:17:27.092+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T11:17:27.114+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T11:17:27.114+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spark_test.py", line 14, in submit_spark_job
    result = subprocess.run(spark_submit_cmd, capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T11:17:27.129+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=test_***_spark, task_id=run_spark_job, run_id=manual__2025-03-26T11:17:25.785500+00:00, execution_date=20250326T111725, start_date=20250326T111726, end_date=20250326T111727
[2025-03-26T11:17:27.142+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task run_spark_job ([Errno 13] Permission denied: 'spark-submit'; 4572)
[2025-03-26T11:17:27.165+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T11:17:27.183+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:17:27.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
