[2025-04-05T12:52:00.641+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:52:00.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:50:00+00:00 [queued]>
[2025-04-05T12:52:00.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:50:00+00:00 [queued]>
[2025-04-05T12:52:00.677+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T12:52:00.689+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-05 12:50:00+00:00
[2025-04-05T12:52:00.695+0000] {standard_task_runner.py:63} INFO - Started process 1643 to run task
[2025-04-05T12:52:00.699+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-05T12:50:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpor_p8b8t']
[2025-04-05T12:52:00.700+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask run_iot_producer_script
[2025-04-05T12:52:00.797+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:50:00+00:00 [running]> on host aef507eba48f
[2025-04-05T12:52:01.019+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T12:50:00+00:00'
[2025-04-05T12:52:01.019+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:52:01.041+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T12:52:01.043+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-05T12:52:01.057+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T12:52:01.953+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-05T12:52:01.954+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 26, in <module>
[2025-04-05T12:52:01.955+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-04-05T12:52:01.956+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-04-05T12:52:01.957+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-04-05T12:52:01.958+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-04-05T12:52:01.958+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-04-05T12:52:01.959+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-04-05T12:52:01.960+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-04-05T12:52:01.960+0000] {subprocess.py:93} INFO - 
[2025-04-05T12:52:02.050+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-05T12:52:02.051+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:52:02.062+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-05T12:52:02.065+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-05T12:50:00+00:00, execution_date=20250405T125000, start_date=20250405T125200, end_date=20250405T125202
[2025-04-05T12:52:02.076+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 1643)
[2025-04-05T12:52:02.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T12:52:02.130+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:52:02.131+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
