[2025-04-16T19:15:18.209+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-16T19:15:18.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-16T19:05:00+00:00 [queued]>
[2025-04-16T19:15:18.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-16T19:05:00+00:00 [queued]>
[2025-04-16T19:15:18.237+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-16T19:15:18.246+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-16 19:05:00+00:00
[2025-04-16T19:15:18.249+0000] {standard_task_runner.py:63} INFO - Started process 791 to run task
[2025-04-16T19:15:18.252+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-16T19:05:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmp5uzub3yh']
[2025-04-16T19:15:18.253+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask run_iot_producer_script
[2025-04-16T19:15:18.285+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-16T19:05:00+00:00 [running]> on host 5093da77a75c
[2025-04-16T19:15:18.344+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T19:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T19:05:00+00:00'
[2025-04-16T19:15:18.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-16T19:15:18.357+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-16T19:15:18.357+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-16T19:15:18.366+0000] {subprocess.py:86} INFO - Output:
[2025-04-16T19:15:34.859+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-16T19:15:34.860+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 12, in <module>
[2025-04-16T19:15:34.860+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-04-16T19:15:34.860+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2025-04-16T19:15:34.861+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-04-16T19:15:34.861+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 234, in __init__
[2025-04-16T19:15:34.862+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2025-04-16T19:15:34.862+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 929, in check_version
[2025-04-16T19:15:34.862+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-04-16T19:15:34.862+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-04-16T19:15:34.893+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-16T19:15:34.894+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-16T19:15:34.902+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-16T19:15:34.904+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-16T19:05:00+00:00, execution_date=20250416T190500, start_date=20250416T191518, end_date=20250416T191534
[2025-04-16T19:15:34.916+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 791)
[2025-04-16T19:15:34.959+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-16T19:15:35.001+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T19:15:35.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
