[2025-04-15T21:49:17.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-15T21:49:18.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-15T21:40:00+00:00 [queued]>
[2025-04-15T21:49:18.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-15T21:40:00+00:00 [queued]>
[2025-04-15T21:49:18.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-15T21:49:18.158+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-15 21:40:00+00:00
[2025-04-15T21:49:18.180+0000] {standard_task_runner.py:63} INFO - Started process 1076 to run task
[2025-04-15T21:49:18.193+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-15T21:40:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmphc8xwmfj']
[2025-04-15T21:49:18.202+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_iot_producer_script
[2025-04-15T21:49:18.397+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-15T21:40:00+00:00 [running]> on host 5093da77a75c
[2025-04-15T21:49:18.607+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T21:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T21:40:00+00:00'
[2025-04-15T21:49:18.609+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-15T21:49:18.680+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-15T21:49:18.681+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-15T21:49:18.731+0000] {subprocess.py:86} INFO - Output:
[2025-04-15T21:49:20.896+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-15T21:49:20.898+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 35, in <module>
[2025-04-15T21:49:20.900+0000] {subprocess.py:93} INFO -     cursor.execute("""
[2025-04-15T21:49:20.901+0000] {subprocess.py:93} INFO - psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
[2025-04-15T21:49:20.901+0000] {subprocess.py:93} INFO - DETAIL:  Key (typname, typnamespace)=(iot_raw_data_id_seq, 2200) already exists.
[2025-04-15T21:49:20.902+0000] {subprocess.py:93} INFO - 
[2025-04-15T21:49:21.373+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-15T21:49:21.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-15T21:49:21.434+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T21:49:21.451+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-15T21:40:00+00:00, execution_date=20250415T214000, start_date=20250415T214918, end_date=20250415T214921
[2025-04-15T21:49:21.506+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 1076)
[2025-04-15T21:49:21.547+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-15T21:49:21.588+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
