[2025-04-17T23:15:17.450+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-17T23:15:17.472+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-17T23:05:00+00:00 [queued]>
[2025-04-17T23:15:17.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-17T23:05:00+00:00 [queued]>
[2025-04-17T23:15:17.477+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-17T23:15:17.487+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-17 23:05:00+00:00
[2025-04-17T23:15:17.490+0000] {standard_task_runner.py:63} INFO - Started process 1190 to run task
[2025-04-17T23:15:17.493+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-17T23:05:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpft5ntuuz']
[2025-04-17T23:15:17.494+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask run_iot_producer_script
[2025-04-17T23:15:17.526+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-17T23:05:00+00:00 [running]> on host 2b5f93c9e322
[2025-04-17T23:15:17.617+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T23:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T23:05:00+00:00'
[2025-04-17T23:15:17.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-17T23:15:17.634+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-17T23:15:17.634+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-17T23:15:17.649+0000] {subprocess.py:86} INFO - Output:
[2025-04-17T23:15:34.201+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-17T23:15:34.203+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 12, in <module>
[2025-04-17T23:15:34.204+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-04-17T23:15:34.204+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2025-04-17T23:15:34.205+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-04-17T23:15:34.206+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 234, in __init__
[2025-04-17T23:15:34.207+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2025-04-17T23:15:34.208+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/kafka/client_async.py", line 929, in check_version
[2025-04-17T23:15:34.208+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-04-17T23:15:34.209+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-04-17T23:15:34.268+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-17T23:15:34.268+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-17T23:15:34.277+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-17T23:15:34.279+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-17T23:05:00+00:00, execution_date=20250417T230500, start_date=20250417T231517, end_date=20250417T231534
[2025-04-17T23:15:34.288+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 1190)
[2025-04-17T23:15:34.300+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-17T23:15:34.311+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T23:15:34.312+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
