[2025-04-05T12:53:01.643+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:53:01.671+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:46:00+00:00 [queued]>
[2025-04-05T12:53:01.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:46:00+00:00 [queued]>
[2025-04-05T12:53:01.677+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-05T12:53:01.688+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-05 12:46:00+00:00
[2025-04-05T12:53:01.694+0000] {standard_task_runner.py:63} INFO - Started process 1719 to run task
[2025-04-05T12:53:01.697+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-05T12:46:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpxp8geqbl']
[2025-04-05T12:53:01.699+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask run_iot_producer_script
[2025-04-05T12:53:01.734+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:46:00+00:00 [running]> on host aef507eba48f
[2025-04-05T12:53:01.790+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T12:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T12:46:00+00:00'
[2025-04-05T12:53:01.791+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:53:01.802+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T12:53:01.802+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-05T12:53:01.812+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T12:53:02.428+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-05T12:53:02.429+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 26, in <module>
[2025-04-05T12:53:02.429+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-04-05T12:53:02.430+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-04-05T12:53:02.431+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-04-05T12:53:02.431+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-04-05T12:53:02.432+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-04-05T12:53:02.433+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-04-05T12:53:02.434+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-04-05T12:53:02.434+0000] {subprocess.py:93} INFO - 
[2025-04-05T12:53:02.487+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-05T12:53:02.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:53:02.498+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-05T12:53:02.500+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-05T12:46:00+00:00, execution_date=20250405T124600, start_date=20250405T125301, end_date=20250405T125302
[2025-04-05T12:53:02.514+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 1719)
[2025-04-05T12:53:02.550+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T12:53:02.586+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:53:02.588+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
