[2025-04-15T20:43:44.580+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-15T20:43:44.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script manual__2025-04-15T20:43:43.973459+00:00 [queued]>
[2025-04-15T20:43:44.725+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script manual__2025-04-15T20:43:43.973459+00:00 [queued]>
[2025-04-15T20:43:44.726+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-15T20:43:44.755+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-15 20:43:43.973459+00:00
[2025-04-15T20:43:44.769+0000] {standard_task_runner.py:63} INFO - Started process 926 to run task
[2025-04-15T20:43:44.776+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'manual__2025-04-15T20:43:43.973459+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpkvvvt0jj']
[2025-04-15T20:43:44.781+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask run_iot_producer_script
[2025-04-15T20:43:44.886+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script manual__2025-04-15T20:43:43.973459+00:00 [running]> on host cfceca701afe
[2025-04-15T20:43:45.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T20:43:43.973459+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T20:43:43.973459+00:00'
[2025-04-15T20:43:45.086+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-15T20:43:45.145+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-15T20:43:45.146+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-15T20:43:45.169+0000] {subprocess.py:86} INFO - Output:
[2025-04-15T20:43:46.113+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-15T20:43:46.114+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 35, in <module>
[2025-04-15T20:43:46.114+0000] {subprocess.py:93} INFO -     cursor.execute("""
[2025-04-15T20:43:46.114+0000] {subprocess.py:93} INFO - psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
[2025-04-15T20:43:46.114+0000] {subprocess.py:93} INFO - DETAIL:  Key (typname, typnamespace)=(iot_raw_data_id_seq, 2200) already exists.
[2025-04-15T20:43:46.114+0000] {subprocess.py:93} INFO - 
[2025-04-15T20:43:46.208+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-15T20:43:46.209+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-15T20:43:46.229+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T20:43:46.234+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=manual__2025-04-15T20:43:43.973459+00:00, execution_date=20250415T204343, start_date=20250415T204344, end_date=20250415T204346
[2025-04-15T20:43:46.254+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 926)
[2025-04-15T20:43:46.273+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-15T20:43:46.296+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T20:43:46.298+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
