[2025-04-05T12:54:00.406+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:54:00.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:52:00+00:00 [queued]>
[2025-04-05T12:54:00.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:52:00+00:00 [queued]>
[2025-04-05T12:54:00.434+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T12:54:00.442+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-05 12:52:00+00:00
[2025-04-05T12:54:00.447+0000] {standard_task_runner.py:63} INFO - Started process 1795 to run task
[2025-04-05T12:54:00.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-05T12:52:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpcxsk9nwl']
[2025-04-05T12:54:00.451+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask run_iot_producer_script
[2025-04-05T12:54:00.486+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:52:00+00:00 [running]> on host aef507eba48f
[2025-04-05T12:54:00.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T12:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T12:52:00+00:00'
[2025-04-05T12:54:00.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:54:00.554+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T12:54:00.555+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/script/iot_data_producer.py']
[2025-04-05T12:54:00.563+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T12:54:01.168+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-05T12:54:01.169+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/script/iot_data_producer.py", line 26, in <module>
[2025-04-05T12:54:01.171+0000] {subprocess.py:93} INFO -     conn = psycopg2.connect(
[2025-04-05T12:54:01.171+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
[2025-04-05T12:54:01.172+0000] {subprocess.py:93} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2025-04-05T12:54:01.173+0000] {subprocess.py:93} INFO - psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-04-05T12:54:01.173+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-04-05T12:54:01.174+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-04-05T12:54:01.175+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-04-05T12:54:01.176+0000] {subprocess.py:93} INFO - 
[2025-04-05T12:54:01.230+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-05T12:54:01.231+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:54:01.241+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-05T12:54:01.244+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-05T12:52:00+00:00, execution_date=20250405T125200, start_date=20250405T125400, end_date=20250405T125401
[2025-04-05T12:54:01.253+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 1.; 1795)
[2025-04-05T12:54:01.262+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T12:54:01.274+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:54:01.276+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
